#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Obtén el nombre de la rama actual
RAMA_ACTUAL=$(git symbolic-ref --short HEAD)

# Función para ejecutar el lint con correcciones
ejecutarLintConCorrecciones() {
  npm run fix:lint
}

# Función para ejecutar el lint y solicitar confirmación
ejecutarLintConConfirmacion() {
  read -p "¿Deseas continuar con el lint en la rama $RAMA_ACTUAL? (y/n): " confirmar
  if [ "$confirmar" = "y" ]; then
    npm run lint
  else
    echo "Commit cancelado."
    exit 1
  fi
}

# Verifica si hay pendiente de jalar en la rama actual
if [ "$RAMA_ACTUAL" != "main" ]; then
  git fetch origin
  CAMBIOS_PENDIENTES=$(git rev-list HEAD..origin/main)

  if [ "$CAMBIOS_PENDIENTES" != "" ]; then
    echo "Tienes cambios pendientes por jalar desde main. Por favor, actualiza tu rama antes de hacer el commit."
    exit 1
  fi
fi

# Ejecuta comandos según la rama actual
if [ "$RAMA_ACTUAL" = "develop" ] || [ "$RAMA_ACTUAL" = "main" ]; then
  ejecutarLintConCorrecciones
else
  ejecutarLintConConfirmacion
fi
