#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Obtén el nombre de la rama actual
RAMA_ACTUAL=$(git symbolic-ref --short HEAD)

# Función para ejecutar el lint con correcciones
ejecutarLintConCorrecciones() {
  npm run fix:lint
  echo "Lint ejecutado con correcciones."
}

# Función para ejecutar el lint
ejecutarLint() {
  npm run lint
  echo "Lint ejecutado sin correcciones."
}

# Verifica si hay pendiente de jalar en la rama actual (excepto main)
if [ "$RAMA_ACTUAL" != "main" ]; then
  git fetch origin
  CAMBIOS_PENDIENTES=$(git rev-list HEAD..origin/main)

  if [ "$CAMBIOS_PENDIENTES" != "" ]; then
    echo "Tienes cambios pendientes por jalar desde main. Por favor, actualiza tu rama antes de hacer el commit."
    exit 1
  fi
fi

# Ejecuta comandos según la rama actual
if [ "$RAMA_ACTUAL" = "develop" ]; then
  ejecutarLintConCorrecciones
elif [ "$RAMA_ACTUAL" = "main" ]; then
  ejecutarLintConCorrecciones
else
  ejecutarLint
fi
